### PR TITLE
Distance scale not required when printing slider values

### PR DESCRIPTION
**Pull request by dkhughes**
The values from the sliders are already in the correct units, no need to scale according to their ratio with mm.

### CODE REVIEW

**Comment by machinekoder** [comment]
@dkhughes Do you use inch or mm as machine units?

**Comment by dkhughes** [comment]
I'm using inches.

**Comment by machinekoder** [comment]
Okay, I have not tested QtQuickVcp with inches as machine units so far. It would be great if you could try out the various combinations (machine units + G20/G21 active).

**Comment by dkhughes** [comment]
Good point. I'm not sure how linuxcnc publishes units when changing G20/G21, but I bet we will have to look at the mode, and the underlying machine units to figure out conversions at the gui.

 I will test this out soon and report back hopefully with working patches.

**Comment by machinekoder** [comment]
Machinekit reports units in two places:
* [machine units](https://github.com/machinekit/machinetalk-protobuf/blob/master/src/machinetalk/protobuf/status.proto#L316)
* [program units](https://github.com/machinekit/machinetalk-protobuf/blob/master/src/machinetalk/protobuf/status.proto#L460)

Machine units are defined in the INI file, program units by the interpreter when executing G20/G21.

I have tested QtQuickVcp with using mm as machine units.

**Comment by dkhughes** [comment]
The addition of machine units to the helper coupled with the current interpreter units seems to fix this issue. I will clean up a branch that will merge and resubmit a new PR.

**Pull request closed without merging**
